[package]
name = "converter"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
mesh-tools.workspace = true
basis-universal.workspace = true
ddsfile.workspace = true
nom.workspace = true
nom-derive.workspace = true
rusqlite.workspace = true
rkyv.workspace = true
color-eyre.workspace = true
memmap2 = "0.9.11"
flate2   = "1.1.9"
rayon = "1.12.0"
crossbeam-channel.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
walkdir.workspace = true
lz4_flex.workspace = true
image_dds.workspace = true
ktx2.workspace = true
project-wormhole-nif.workspace = true
project-wormhole-esm.workspace = true
mlua.workspace = true

[dev-dependencies]
tempfile = "3.20"
ruzstd = "0.8"
dummy-content = { path = "../dummy-content" }
project-wormhole-shared = "0.1.0"

[build-dependencies]
cc = "1.2"
